name: Build vote app and push to docker

on:
  push:
    branches:
      - 'feature'
    paths:
      - 'vote/**'
      - '.github/workflows/ci-vote.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set variables
        id: vars
        run: |
          # Get branch name and short hash
          BRANCH=${GITHUB_REF_NAME}
          SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-5)

          # save output for use in another steps
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image and push to docker hub
        uses: docker/build-push-action@v6
        with:
          context: ./vote
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vote:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}